# Week 5 Exercises - LU decomposition, Matrix inversion and Gauss-Seidel
Introduction to Numerical Problem Solving, Spring 2017   
28.2.2017, Luong Nguyen  
Helsinki Metropolia University of Applied Sciences

In [54]:
# Initial import statements
from pprint import pprint
from numpy import *
from scipy.linalg import lu, solve, inv, det

## Problem 3
Write a Python program that solves $Ax = b$ using LU decomposition. Use the functions LUdecomp and LUsolve. 
  
$A = 
 \begin{bmatrix}
    1 & 4 & 1 \\
    1 & 6 & -1\\
    2 & -1 & 2
 \end{bmatrix} 
 ,\enspace  b =
 \begin{bmatrix}
    7 \\
    13\\
    5
 \end{bmatrix}$

What are values for the lower and upper triangular matrices $L$ and $U$?



### Solution
Because the code in the lecture did not work very well, instead of writing a program, we are recommended to use the function imported from scipy.linalg to solve the equation.
First, we use function lu to decompose A into P, L, U.  
Second, we use function solve to find y from the equation $PLy = b$  
Finally, we use function solve to find x from the equation $Ux = y$  

To check the result, we compare it with the solution from solve(A, b)

In [55]:
A = array([[1, 4, 1], [1, 6, -1], [2, -1, 2]])
b = array([7, 13, 5])
P, L, U = lu(A)
print("Lower triangular matrix:")
pprint(L)
print("Upper triangular matrix:")
pprint(U)
y = solve(dot(P, L), b)
x = solve(U, y)

print("x: ")
pprint(x)


Lower triangular matrix:
array([[ 1.        ,  0.        ,  0.        ],
       [ 0.5       ,  1.        ,  0.        ],
       [ 0.5       ,  0.69230769,  1.        ]])
Upper triangular matrix:
array([[ 2.        , -1.        ,  2.        ],
       [ 0.        ,  6.5       , -2.        ],
       [ 0.        ,  0.        ,  1.38461538]])
x: 
array([ 5.,  1., -2.])


In [56]:
# check the answer
A = array([[1, 4, 1], [1, 6, -1], [2, -1, 2]])
b = array([7, 13, 5])
pprint(solve(A, b))

array([ 5.,  1., -2.])


### Since the answer are the same, we did get the right solution.
$x = \begin{bmatrix}
    5\\ 1\\ -2
 \end{bmatrix}$

## Problem 6
Invert the following matrices with any method  
  
 $A =
 \begin{bmatrix}
    5 & -3 & -1 & 0 \\
    -2 & 1 & 1 & 1\\
    3 & -5 & 1 & 2\\
    0 & 8 & -4 & -3
 \end{bmatrix}
 \enspace B =
 \begin{bmatrix}
    1 & 3 & -9 & 6 & 4 \\
    2 & -1 & 6 & 7 & 1 \\
    3 & 2 & -3 & 15 & 5 \\
    8 & -1 & 1 & 4 & 2 \\
    11 & 1 & -2 & 18 & 7
 \end{bmatrix}$

Comment on the reliability of the results.


### Solution
First, we use function inv to get the inverse matrix of matrix A and B.
We check the reliabilty of the results by taking dot product of each matrix A and B with its inverse. If we get the result as an identity matrix, the inverse is correct. 

In [57]:
A = array([5, -3, -1, 0, -2, 1, 1, 1, 3, -5, 1, 2, 0, 8, -4, -3]).reshape(4, 4)
print("Inverse matrix of A:")
pprint(around(inv(A),8))
print("Dot product of A and inverse of A:")
pprint(around(dot(A, inv(A))))

B = array([1, 3, -9, 6, 4, 2, -1, 6, 7, 1, 3, 2, -3, 15, 5, 8, -1, 1, 4, 2, 11, 1, -2, 18, 7]).reshape(5,5)
print("Inverse matrix of B:")
pprint(around(inv(B),8))
print("Dot product of B and inverse of B:")
pprint(around(dot(inv(B), B)))
print("Determinant of matrix B:")
pprint(around(det(B),10))

Inverse matrix of A:
array([[ 1.125 ,  1.    , -0.875 , -0.25  ],
       [ 0.8125,  1.    , -0.6875, -0.125 ],
       [ 2.1875,  2.    , -2.3125, -0.875 ],
       [-0.75  , -0.    ,  1.25  ,  0.5   ]])
Dot product of A and inverse of A:
array([[ 1.,  0.,  0., -0.],
       [-0.,  1., -0., -0.],
       [-0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])
Inverse matrix of B:
array([[ -7.42166231e+14,  -7.42166231e+14,  -7.42166231e+14,
         -1.48433246e+15,   1.48433246e+15],
       [ -3.52528960e+15,  -3.52528960e+15,  -3.52528960e+15,
         -7.05057919e+15,   7.05057919e+15],
       [ -5.90359502e+14,  -5.90359502e+14,  -5.90359502e+14,
         -1.18071900e+15,   1.18071900e+15],
       [ -3.33333330e-01,  -3.33333330e-01,   6.66666670e-01,
          3.33333330e-01,  -3.33333330e-01],
       [  1.50119988e+15,   1.50119988e+15,   1.50119988e+15,
          3.00239975e+15,  -3.00239975e+15]])
Dot product of B and inverse of B:
array([[ 2., -0., -1.,  0.,  2.],
       [ 0.,  2., -2

#### The inverse of matrix A is correct since we obtain an identity matrix when calculate the dot product of A and its inverse. The inverse of matrix B that we get is not correct because we did not get an identity matrix for the dot product of B and its inverse. Since the determinant B is 0, matrix B does not have an inverse.

## Problem 9
Use the Gauss-Seidel with relaxation to solve $Ax = b$, where  
  
$A = 
 \begin{bmatrix}
    4 & -1 & 0 & 0 \\
    -1 & 4 & -1 & 0 \\
    0 & -1 & 4 & -1 \\
    0 & 0 & -1 & 3
 \end{bmatrix} 
 \enspace  b =
 \begin{bmatrix}
    15 \\
    10 \\
    10 \\
    10
 \end{bmatrix}$

Take $x_i = b_i/A_{ii}$ as the starting vector, and use $\omega$ = 1.1 for the relaxation factor


### Solution
First, we implement the gaussSeidel function with relaxation based on the function without relaxation from the lecture. There is just one small change that omega will be taken into account when calculate x[i].  
We also need to calculate the starting value of vector x (x0) which $x_i = b_i/A_{ii}$.  
Finally we call the function with matrix A and b, x0 and omega = 1.1 as arguments.  

In [58]:
def gaussSeidel(A, b, x0, omega):
    x = x0
    for k in range(100):
        for i in range(n):
            s = 0
            for j in range(n):
                if j != i:
                    s += A[i, j] * x[j]
            x[i] = omega/A[i, i] * (b[i] - s) + (1 - omega)/x[i]
    return x

A = array([4, -1, 0, 0, -1, 4, -1, 0, 0, -1, 4, -1, 0, 0, -1, 3]).reshape(4, 4)
b = array([15, 10, 10, 10])  
# find x0 
n = len(b)
x0 = zeros(n)
for i in range(len(x0)):
    x0[i] = b[i] / A[i, i]
    
pprint(gaussSeidel(A, b, x0, 1.1))
print('Solution by solve function: ')
pprint(solve(A, b))

array([ 5.74583856,  5.95724531,  5.97791267,  5.84144894])
Solution by solve function: 
array([ 5.,  5.,  5.,  5.])


#### Using Gauss-Seidel with relaxation we are able to get an answer. It is not the correct solution given by the solve function. It is because the use of relaxation which improves the convergence of this method. We can get better result if we recalculate omega on each iteration. For this problem, if we do not use relaxation (omega = 1), we will be able to get the correct result.

In [59]:
pprint(gaussSeidel(A, b, x0, 1))

array([ 5.,  5.,  5.,  5.])
