In [3]:
from numpy import *
from numpy.linalg import inv, det, solve

### Problem 1
Find the solution for the given system of equations

In [26]:
A = array([[3., -0.1, -0.2], [0.1, -7., -0.3], [0.3, -0.2, -10.]])
b = array([7.85, -19.3, 71.4])
x = solve(A, b)
print(x)

[ 2.2441941   3.09497021 -7.13457358]


In [9]:
A[1] = A[1] * 2 - A[0]
A

array([[  3. ,  -0.1,  -0.2],
       [ -2.8, -13.9,  -0.4],
       [  0.3,  -0.2, -10. ]])

In [4]:
x = dot(inv(A), b)
x

array([ 2.2441941 ,  3.09497021, -7.13457358])

In [16]:
A = array([[3., -0.1, -0.2], [0.1, -7., -0.3], [0.3, -0.2, -10.]])
b = array([7.85, -19.3, 71.4])
RowsA, ColsA = shape(A)
Rowsb = shape(b)
for i in range(RowsA-1):
        for j in range(i+1, RowsA):
            factor = A[i,i] / A[j,i]
            print(factor)
            A[j] = factor * A[j] - A[i]
            b[j] = factor * b[j] - b[i]
            print(A)
            print(b)
print(i, j)

30.0
[[  3.00000000e+00  -1.00000000e-01  -2.00000000e-01]
 [  0.00000000e+00  -2.09900000e+02  -8.80000000e+00]
 [  3.00000000e-01  -2.00000000e-01  -1.00000000e+01]]
[   7.85 -586.85   71.4 ]
10.0
[[  3.00000000e+00  -1.00000000e-01  -2.00000000e-01]
 [  0.00000000e+00  -2.09900000e+02  -8.80000000e+00]
 [  0.00000000e+00  -1.90000000e+00  -9.98000000e+01]]
[   7.85 -586.85  706.15]
110.473684211
[[  3.00000000e+00  -1.00000000e-01  -2.00000000e-01]
 [  0.00000000e+00  -2.09900000e+02  -8.80000000e+00]
 [  0.00000000e+00   0.00000000e+00  -1.10164737e+04]]
[  7.85000000e+00  -5.86850000e+02   7.85978421e+04]
1 2


In [9]:
def pivot(A, row1, row2):
    temp = A[row2].copy()
    A[row2] = A[row1]
    A[row1] = temp
    return A
def gaussian(A, b):
    RowsA, ColsA = shape(A)
    Rowsb = shape(b)[0]
    x = zeros(Rowsb)
            
    # elimination
    for i in range(RowsA-1):
        # partial pivot
        r = argmax(abs(A[i:, i])) + i
#         print(r)
        if r != i:
            # pivot
            A = pivot(A, i, r)
            b = pivot(b, i, r)
#         print(A)
        for j in range(i+1, RowsA):
            if (A[j,i] != 0):
                factor = A[i,i] / A[j,i]
                A[j] = factor * A[j] - A[i]
                b[j] = factor * b[j] - b[i]
            
    # back substitution
    for i in range(Rowsb-1, -1, -1):
        x[i] = (b[i] - dot(A[i, i+1:], x[i+1:])) / A[i,i]
    return x  

In [11]:
A = array([[4., -2, 1], [-2, 4, -2], [1, -2, 4]])
b = array([11, -16, 17])
x = gaussian(A, b)
print(x)

[ 1. -2.  3.]


In [8]:
dot(A, x)

array([ 11.,  21.,  36.])

In [80]:
A = array([[3., -0.1, -0.2], [0.1, -7., -0.3], [0.3, -0.2, -10.]])
b = array([7.85, -19.3, 71.4])
gaussian(A, b)

array([ 2.2441941 ,  3.09497021, -7.13457358])

In [89]:
A = array([[0, 2, 3], [4, 6, 7], [2, 1, 6]])
b = array([2, -3, 5])
gaussian(A, b)

1
[[4 6 7]
 [0 2 3]
 [2 1 6]]
2
[[ 4  6  7]
 [ 0 -4  5]
 [ 0  2  3]]


array([-1.47727273, -1.31818182,  1.54545455])