# Week 14b - Review and Peer evaluation
Introduction to Numerical Problem Solving, Spring 2017    
CC BY-NC-SA, Sakari Lukkarinen
Helsinki Metropolia University of Applied Sciences

## Instructions

The aim of this notebook is to help you to review for the final test and earn some last points for this course. The notebook contains links to to the lecture notes, problems and student's answers to the home assignments. All identities are cleared out from the answers and the order of them are randomized using Python's random generator functions. Only the instructor and author him/herself might recognize who has done them.

The instructions are the following:

1. First, run all cells. That generates random numbers for each week. Each random number corresponds to one of the answers in the OMA system.
2. Review the lecture notes and the problems for each week by following the links.
3. Open and read the given answers (random choices) one-by-one.
4. After reading each answer, open the peer evaluation form and follow the instructions there.

You need to use your Metropolia's Google account (account@metropolia.fi) in order to open the evaluation form. If you haven't use Metropolia's Google Documents before, please follow the instruction given in: [Cloud Services at Metropolia](https://wiki.metropolia.fi/display/itservices/Cloud+services).

If have any difficulties or have questions concerning this bonus assignment, contact me by email as soon as possible.

Best Regards,

Sakari

In [1]:
%pylab inline
from numpy.random import choice

Populating the interactive namespace from numpy and matplotlib


## Week 9 - Root Finding

* [Lecture notes](https://oma.metropolia.fi/delegate/download_workspace_attachment/4814396/09%20Root%20finding.pdf)

* [Problems](https://oma.metropolia.fi/tyotilat?p_p_id=WorkspacePortlet_WAR_workspaceportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.action=%2Fworkspace%2Fassignments_teacher%2Ftask-view-teacher&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.mode=view&workspace.id=340002155&taskId=312149677&workspaceStudentCount=23)

No peer evaluation answers for this week.

## Week 10 - Root Finding - Part 2

* [Lecture notes](https://oma.metropolia.fi/delegate/download_workspace_attachment/4830162/10%20Root%20finding%20%E2%80%93%20Part%202.pdf)

* [Problems](https://oma.metropolia.fi/tyotilat?p_p_id=WorkspacePortlet_WAR_workspaceportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.action=%2Fworkspace%2Fassignments_teacher%2Ftask-view-teacher&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.mode=view&workspace.id=340002155&taskId=312150014&workspaceStudentCount=23)
* [Answers](https://oma.metropolia.fi/tyotilat?p_p_id=WorkspacePortlet_WAR_workspaceportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.action=%2Fworkspace%2Fdocuments%2Findex&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.mode=view&workspace.id=340002155&workspace.name=Introduction%20to%20Numerical%20Problem%20Solving%20TX00BY09-3007&currentFolder=4900072&orderBy=name&ascending=)


Select the answers to peer evaluate and open the [peer evaluation form](https://goo.gl/forms/TWbLPqCjiADExVG93):

In [2]:
choice(arange(1, 11), 4, replace = False)

array([ 4,  7, 10,  8])

## Week 11 - Optimization

* [Lecture notes](https://oma.metropolia.fi/delegate/download_workspace_attachment/4845004/11%20Optimization.pdf)

* [Problems](https://oma.metropolia.fi/tyotilat?p_p_id=WorkspacePortlet_WAR_workspaceportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.action=%2Fworkspace%2Fassignments_teacher%2Ftask-view-teacher&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.mode=view&workspace.id=340002155&taskId=312150721&workspaceStudentCount=23)

* [Answers](https://oma.metropolia.fi/tyotilat?p_p_id=WorkspacePortlet_WAR_workspaceportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.action=%2Fworkspace%2Fdocuments%2Findex&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.mode=view&workspace.id=340002155&workspace.name=Introduction%20to%20Numerical%20Problem%20Solving%20TX00BY09-3007&currentFolder=4900084&orderBy=name&ascending=)


Select the answers to peer evaluate and open the [peer evaluation form](https://goo.gl/forms/TWbLPqCjiADExVG93):

In [3]:
choice(arange(1, 9), 4, replace = False)

array([3, 1, 7, 8])

## Week 12 - Curve fitting

* [Lecture notes](https://oma.metropolia.fi/delegate/download_workspace_attachment/4866848/12%20Curve%20Fitting.pdf)

* [Problems](https://oma.metropolia.fi/tyotilat?p_p_id=WorkspacePortlet_WAR_workspaceportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.action=%2Fworkspace%2Fassignments_teacher%2Ftask-view-teacher&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.mode=view&workspace.id=340002155&taskId=312150809&workspaceStudentCount=23)

* [Answers](https://oma.metropolia.fi/tyotilat?p_p_id=WorkspacePortlet_WAR_workspaceportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.action=%2Fworkspace%2Fdocuments%2Findex&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.mode=view&workspace.id=340002155&workspace.name=Introduction%20to%20Numerical%20Problem%20Solving%20TX00BY09-3007&currentFolder=4900104&orderBy=name&ascending=)


Select the answers to peer evaluate and open the [peer evaluation form](https://goo.gl/forms/TWbLPqCjiADExVG93):

In [4]:
choice(arange(1, 12), 4, replace = False)

array([6, 4, 9, 3])

## Week 13 - Integration

* [Lecture notes](https://oma.metropolia.fi/delegate/download_workspace_attachment/4881964/13.%20Numerical%20Integration%20and%20Differentiation.pdf)

* [Problems](https://oma.metropolia.fi/tyotilat?p_p_id=WorkspacePortlet_WAR_workspaceportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.action=%2Fworkspace%2Fassignments_teacher%2Ftask-view-teacher&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.mode=view&workspace.id=340002155&taskId=312150810&workspaceStudentCount=23)

* [Answers](https://oma.metropolia.fi/tyotilat?p_p_id=WorkspacePortlet_WAR_workspaceportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.action=%2Fworkspace%2Fdocuments%2Findex&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.mode=view&workspace.id=340002155&workspace.name=Introduction%20to%20Numerical%20Problem%20Solving%20TX00BY09-3007&currentFolder=4900244&orderBy=name&ascending=)


Select the answers to peer evaluate and open the [peer evaluation form](https://goo.gl/forms/TWbLPqCjiADExVG93):

In [5]:
choice(arange(1, 12), 4, replace = False)

array([4, 8, 6, 7])

## Week 14 - Review

* [Problems](https://oma.metropolia.fi/tyotilat?p_p_id=WorkspacePortlet_WAR_workspaceportlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=column-1&p_p_col_count=1&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.action=%2Fworkspace%2Fassignments_teacher%2Ftask-view-teacher&_WorkspacePortlet_WAR_workspaceportlet_struts.portlet.mode=view&workspace.id=340002155&taskId=312151385&workspaceStudentCount=23)

Nothing to peer evaluate.