In [8]:
from pprint import pprint
from numpy import *
from scipy.linalg import lu, solve
from numpy.linalg import inv, det

### Exercise 1

In [8]:
L = array([[1, 0, 0], [1, 1, 0], [1, 5/3, 1]])
U = array([[1, 2, 4], [0, 3, 21], [0, 0 , 0]])
A = dot(L, U)
pprint(A)

array([[  1.,   2.,   4.],
       [  1.,   5.,  25.],
       [  1.,   7.,  39.]])


### Exercise 2

In [15]:
L = array([[1, 0, 0], [3/2, 1, 0], [1/2, 11/13, 1]])
U = array([[2, -3, -1], [0, 13/2, -7/2], [0, 0, 32/13]])
b = array([1, -1, 2])

y = solve(L, b)
x = solve(U, y)
pprint(x)

array([ 1.84375,  0.40625,  1.46875])


In [7]:
# L = array([[1, 0, 0], [1, 1, 0], [1, 5/3, 1]])
# U = array([[1, 2, 4], [0, 3, 21], [0, 0 , 0]])
# A = dot(L, U)

def LUdecomp(a):
    n = len(a)
    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i, k] / a[k, k]
#                 a[i] -= lam * a[k]
                a[i, k+1:n] = a[i, k+1:n] - lam*a[k, k+1:n]
                a[i, k] = lam
    return a


def LUsolve(a, b):
    n = len(a)
    for k in range(1, n):
        b[k] = b[k] - dot(a[k, 0:k], b[0:k])
#     b[n-1] /= a[n-1, n-1]
    for k in range(n-1, -1, -1):
        b[k] = (b[k] - dot(a[k, k+1:n], b[k+1:n])) / a[k, k]
    return b

A = array([[1, 4, 1], [1, 6, -1], [2, -1, 2]])
b = array([7, 13, 5])

pprint(LUdecomp(A))
LUsolve(A, b)

array([[ 1,  4,  1],
       [ 1,  2, -2],
       [ 2, -4, -9]])


array([ 0,  2, -1])

In [53]:
A = array([[1, 4, 1], [1, 6, -1], [2, -1, 2]])
b = array([7, 13, 5])
gaussian(A, b)

array([ 5.,  1., -2.])

In [54]:
A = array([[1, 4, 1], [1, 6, -1], [2, -1, 2]])
b = array([7, 13, 5])
solve(A, b)

array([ 5.,  1., -2.])

In [45]:
A = array([7, 3, -1, 2, 3, 8, 1, -4, -1, 1, 4, -1, 2, -4, -1, 6]).reshape(4, 4)
pprint(A)
b = array([1, 2, 3, 4])
LUdecomp(A)
LUsolve(A, b)

array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])


array([0, 1, 1, 2])

In [101]:
# Helper function, switch 2 rows of a matrix
def pivot(A, row1, row2):
    temp = A[row2].copy()
    A[row2] = A[row1]
    A[row1] = temp
    return A

# implement Gaussian elimination method
def gaussian(A, b):
    RowsA, ColsA = shape(A)
    Rowsb = shape(b)[0]
    x = zeros(Rowsb)
            
    # elimination
    for i in range(RowsA-1):
        # partial pivot
        r = argmax(abs(A[i:, i])) + i
        if r != i:
            # pivot
            A = pivot(A, i, r)
            b = pivot(b, i, r)
        for j in range(i+1, RowsA):
            if (A[j,i] != 0):
                factor = A[i,i] / A[j,i]
                A[j] = factor * A[j] - A[i]
                b[j] = factor * b[j] - b[i]
            
    # back substitution
    for i in range(Rowsb-1, -1, -1):
        x[i] = (b[i] - dot(A[i, i+1:], x[i+1:])) / A[i,i]
    return x 

A = array([7.0, 3, -1, 2, 3, 8, 1, -4, -1, 1, 4, -1, 2, -4, -1, 6]).reshape(4, 4)
pprint(A)
b = array([1, 2, 3, 4])
gaussian(A,b)

array([[ 7.,  3., -1.,  2.],
       [ 3.,  8.,  1., -4.],
       [-1.,  1.,  4., -1.],
       [ 2., -4., -1.,  6.]])


array([-1.15331939,  1.70089326,  0.59927197,  2.28491397])

In [102]:
A = array([7.0, 3, -1, 2, 3, 8, 1, -4, -1, 1, 4, -1, 2, -4, -1, 6]).reshape(4, 4)
b = array([1, 2, 3, 4])
solve(A, b)

array([-1.27619048,  1.87619048,  0.57142857,  2.43809524])

In [56]:
A = array([7, 3, -1, 2, 3, 8, 1, -4, -1, 1, 4, -1, 2, -4, -1, 6]).reshape(4, 4)
b = array([1, 2, 3, 4])
gaussian(A, b)

array([-1.38757116,  2.04411765,  0.56451613,  2.57258065])

In [30]:
A = array([[1, 4, 1], [1, 6, -1], [2, -1, 2]])
b = array([7, 13, 5])
solve(A, b)

array([ 5.,  1., -2.])

In [31]:
A = array([[1, 4, 1], [1, 6, -1], [2, -1, 2]])
len(A)

3

### Exercise 4

In [34]:
def matInv(a):
    n = len(a[0])
    aInv = identity(n)
    a = LUdecomp(a)
    for i in range(n):
        aInv[:, i] = LUsolve(a, aInv[:, i])
    return aInv
A = array([7, 3, -1, 2, 3, 8, 1, -4, -1, 1, 4, -1, 2, -4, -1, 6]).reshape(4, 4)
pprint(A)
matInv(A)

array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])


array([[ 0.14285714, -0.07142857,  0.10714286, -0.28571429],
       [ 0.        ,  0.16666667, -0.08333333,  0.33333333],
       [ 0.        ,  0.        ,  0.5       ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.5       ]])

In [86]:

def inverse(A):
    n = len(A)
    B = identity(n)
    return solve(A, B)
# Ex6
B = array([1, 3, -9, 6, 4, 2, -1, 6, 7, 1, 3, 2, -3, 15, 5, 8, -1, 1, 4, 2, 11, 1, -2, 18, 7]).reshape(5,5)
pprint(around(inverse(B), 8))



array([[ -7.42166231e+14,  -7.42166231e+14,  -7.42166231e+14,
         -1.48433246e+15,   1.48433246e+15],
       [ -3.52528960e+15,  -3.52528960e+15,  -3.52528960e+15,
         -7.05057919e+15,   7.05057919e+15],
       [ -5.90359502e+14,  -5.90359502e+14,  -5.90359502e+14,
         -1.18071900e+15,   1.18071900e+15],
       [ -3.33333330e-01,  -3.33333330e-01,   6.66666670e-01,
          3.33333330e-01,  -3.33333330e-01],
       [  1.50119988e+15,   1.50119988e+15,   1.50119988e+15,
          3.00239975e+15,  -3.00239975e+15]])


In [68]:

A = array([5, -3, -1, 0, -2, 1, 1, 1, 3, -5, 1, 2, 0, 8, -4, -3]).reshape(4, 4)
print(inv(A))
end = time.time()


[[  1.12500000e+00   1.00000000e+00  -8.75000000e-01  -2.50000000e-01]
 [  8.12500000e-01   1.00000000e+00  -6.87500000e-01  -1.25000000e-01]
 [  2.18750000e+00   2.00000000e+00  -2.31250000e+00  -8.75000000e-01]
 [ -7.50000000e-01  -5.55111512e-16   1.25000000e+00   5.00000000e-01]]
0.0020017623901367188


In [51]:
A = array([5, -3, -1, 0, -2, 1, 1, 1, 3, -5, 1, 2, 0, 8, -4, -3]).reshape(4, 4)
around(inv(A),8)

array([[ 1.125 ,  1.    , -0.875 , -0.25  ],
       [ 0.8125,  1.    , -0.6875, -0.125 ],
       [ 2.1875,  2.    , -2.3125, -0.875 ],
       [-0.75  , -0.    ,  1.25  ,  0.5   ]])

In [76]:
from numpy.random import randint
A = randint(0, 10, 16).reshape(4, 4)
B = randint(0, 10, 4).reshape(1,4)
print(B)

[[5 9 6 9]]


In [82]:
def gaussElimin(a, b):
    n = len(b)
    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i, k] / a[k, k]
                a[i, k+1:n] = a[i, k+1:n] - lam*a[k, k+1:n]
                b[i] = b[i] - lam*b[k]
    for k in range(n-1, -1, -1):
        b[k] = (b[k] - dot(a[k, k+1:n], b[k+1:n]))/a[k, k]
    return b
A = array([7, 3, -1, 2, 3, 8, 1, -4, -1, 1, 4, -1, 2, -4, -1, 6]).reshape(4, 4)
b = array([1, 2, 3, 4])
x = gaussElimin(A,b)
pprint(x)
pprint(dot(A, x) - b)

array([0, 0, 1, 1])
array([ 1, -3,  1,  1])


In [83]:
A = array([7, 3, -1, 2, 3, 8, 1, -4, -1, 1, 4, -1, 2, -4, -1, 6]).reshape(4, 4)
b = array([1, 2, 3, 4])
solve(A, b)

array([-1.27619048,  1.87619048,  0.57142857,  2.43809524])

In [107]:
### Ex6
A = array([5, -3, -1, 0, -2, 1, 1, 1, 3, -5, 1, 2, 0, 8, -4, -3]).reshape(4, 4)
pprint(around(inv(A),8))
pprint(around(dot(A, inv(A))))
pprint(around(dot(inv(A), A)))
pprint(det(A))
B = array([1, 3, -9, 6, 4, 2, -1, 6, 7, 1, 3, 2, -3, 15, 5, 8, -1, 1, 4, 2, 11, 1, -2, 18, 7]).reshape(5,5)
pprint(around(dot(inv(B), B)))
pprint(around(det(B),10))

array([[ 1.125 ,  1.    , -0.875 , -0.25  ],
       [ 0.8125,  1.    , -0.6875, -0.125 ],
       [ 2.1875,  2.    , -2.3125, -0.875 ],
       [-0.75  , -0.    ,  1.25  ,  0.5   ]])
array([[ 1.,  0.,  0., -0.],
       [ 0.,  1.,  0.,  0.],
       [-0.,  0.,  1.,  0.],
       [ 0., -0.,  0.,  1.]])
array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0., -0.,  1.,  0.],
       [-0.,  0.,  0.,  1.]])
15.999999999999984
array([[  4.,   1.,  -2.,   4.,   4.],
       [  0.,  -1.,   4., -48.,  -8.],
       [  0.,   0.,   1.,   0.,  -1.],
       [  0.,   0.,  -0.,   1.,   0.],
       [  0.,   0.,   0.,   8.,   0.]])
0.0


excuse me, for exercise 6, matrix B, I use the inv function import from linalg, but dot(B, inv(B)) does not return an identity matrix. What is the problem here? 

In [9]:
pprint(dot(B, inv(B)))

NameError: name 'B' is not defined

In [ ]:
import numpy as np
import math
A = array([4, -1, 0, 0, -1, 4, -1, 0, 0, -1, 4, -1, 0, 0, -1, 3]).reshape(4, 4)
b = array([15, 10, 10, 10])
n = len(b)
x0 = zeros(n)
for i in range(len(x0)):
    x0[i] = b[i] / A[i, i]
    
def iterEqs(A, b, x, omega):
    for i in range(n):
        s = 0
        for j in range(n):
            if j != i:
                s += A[i, j] * x[j]
        x[i] = omega/A[i, i] * (b[i] - s) + (1 - omega)/x[i]
    return x


def gaussSeidel(A, b, x,tol = 1.0e-9):
    omega = 1.1
    k = 10
    p = 1
    for i in range(1,501):
        xOld = x.copy()
        x = iterEqs(A, b, x,omega)
        dx = math.sqrt(np.dot(x-xOld,x-xOld))
        if dx < tol: return x,i,omega
      # Compute relaxation factor after k+p iterations
        if i == k: dx1 = dx
        if i == k + p:
            dx2 = dx
            omega = 2.0/(1.0 + math.sqrt(1.0  \
                  - (dx2/dx1)**(1.0/p)))
    print('Gauss-Seidel failed to converge')
gaussSeidel(A, b, x0)